units:
  # Proxy Spacing Variables
  # PG1316S keycaps are smaller than chocs...
  # According to https://docs.holykeebs.com/datasheets/PG1316_1U.pdf they are actually 16x16mm
  # but per Mike Holscher this 17x17 spacing works better.
  kx: 17
  ky: 17
  # Padding Variables
  px: kx + 2
  py: ky + 2
  $default_height: 17
  $default_width: 17
points:
  zones:
    hand:
      anchor.shift: [80,-160]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
        ring:
          key:
            stagger: 8
            splay: -4
            spread: kx+2
        middle:
          key:
            stagger: 7
            splay: -3
            spread: kx+1
        index:
          key:
            stagger: -4
            splay: -2
            spread: kx+0.8
        inner:
          key:
            stagger: -2
            splay: -1
            spread: kx+0.6
      rows:
        bottom:
        home:
        top:
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: hand_inner_bottom
        shift: [-2.5,-20]
      columns:
        near:
          key:
            splay: -15
        far:
          key:
            splay: -15
            shift: [3,-2]
      rows:
        fan:
  rotate: 10
  mirror: &mirror
    ref: thumb_far_fan
    distance: 3kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board_left:
    - what: polygon
      operation: stack
      points:
        - ref: thumb_far_fan
          shift: [9,-9]
        - ref: thumb_near_fan
          shift: [-9,-9]
        - ref: hand_pinky_bottom
          shift: [-9,-9.7]
        - ref: hand_pinky_top
          shift: [-9,9]
        - ref: hand_middle_top
          shift: [-9,9]
        - ref: hand_middle_top
          shift: [9,9]
        - ref: hand_inner_top
          shift: [9,9]
        - ref: hand_inner_top
          shift: [31,9]
        - ref: hand_inner_bottom
          shift: [31,-22.3]
      fillet: 3
  slot_left:
    - what: polygon
      operation: stack
      points:
        - ref: hand_inner_top
          shift: [12.5,9]
        - ref: hand_inner_top
          shift: [12.5,-25.5]
        - ref: hand_inner_top
          shift: [24.5,-25.5]
        - ref: hand_inner_top
          shift: [24.5,9]
  combo_left:
    - name: board_left
    - operation: subtract
      name: slot_left
  board_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_thumb_far_fan
          shift: [9,-9]
        - ref: mirror_thumb_near_fan
          shift: [-9,-9]
        - ref: mirror_hand_pinky_bottom
          shift: [-9,-9.7]
        - ref: mirror_hand_pinky_top
          shift: [-9,9]
        - ref: mirror_hand_middle_top
          shift: [-9,9]
        - ref: mirror_hand_middle_top
          shift: [9,9]
        - ref: mirror_hand_inner_top
          shift: [9,9]
        - ref: mirror_hand_inner_top
          shift: [31,9]
        - ref: mirror_hand_inner_bottom
          shift: [31,-22.3]
      fillet: 3
  slot_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_hand_inner_top
          shift: [12.5,9]
        - ref: mirror_hand_inner_top
          shift: [12.5,-25.5]
        - ref: mirror_hand_inner_top
          shift: [24.5,-25.5]
        - ref: mirror_hand_inner_top
          shift: [24.5,9]
  combo_right:
    - name: board_right
    - operation: subtract
      name: slot_right
pcbs:
  slimsplaydy_left_unrouted:
    outlines:
      main:
        outline: combo_left
    footprints:
      pg1316s:
        what: switch_pg1316s_dev
        where: /^hand|^thumb/
        params:
          from: "{{name}}"
          to: GND
          reversable: true
          side: 'B'
          large_p1: false
          square_p1: false
          square_p2: false
          shift_p2: false
          small_mp: false
          pad_vias: true
          pad_via_size: 0.4
          mp_vias: true
          mp_via_size: 0.4
      nicenano:
          what: mcu_nice_nano_smd
          where:
            ref: hand_inner_top
            shift: [18.5,-9]
            rotate: 0
          params:
            reverse_mount: true
            P1: D1
            P1_label: D1
            P0: thumb_far_fan
            P0_label: D0
            P2: thumb_near_fan
            P2_label: D2
            P3: hand_pinky_bottom
            P3_label: D3
            P4: hand_ring_bottom
            P4_label: D4
            P5: hand_inner_bottom
            P5_label: D5
            P6: hand_index_bottom
            P6_label: D6
            P7: hand_pinky_home
            P7_label: D7
            P8: hand_middle_bottom
            P8_label: D8            
            P9: hand_pinky_top
            P9_label: D9
            P10: hand_ring_home
            P10_label: D10
            P16: hand_ring_top
            P16_label: D16
            P14: hand_inner_home
            P14_label: D14
            P15: hand_index_home
            P15_label: D15
            P18: hand_middle_home
            P18_label: D18
            P19: hand_middle_top
            P19_label: D19
            P20: hand_index_top
            P20_label: D20
            P21: hand_inner_top
            P21_label: D21
            VCC: 3V3
            VCC_label: 3V3
            RAW: BAT
            RAW_label: BAT
      power:
        what: slider
        params:
          from: BAT_P
          to: BAT
        where:
          ref: hand_inner_bottom
          shift: [-53,-22]
          rotate: 180
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: hand_inner_bottom
          shift: [-35,-8]
          rotate: 0
      battcon:
        what: battery_connector_molex_pico_ezmate_1x02
        where:
          ref: hand_inner_bottom
          shift: [-56,-16]
          rotate: 90
      batsolder_pos:
        what: pad_single
        where:
          ref: hand_inner_bottom
          shift: [-59.75,-14.5]
          rotate: 0
        params:
          P1: BAT_P
      batsolder_neg:
        what: pad_single
        where:
          ref: hand_inner_bottom
          shift: [-59.75,-17.5]
          rotate: 0
        params:
          P1: GND
      battery:  
        what: battery_301230
        where:
          ref: hand_inner_bottom
          shift: [-30,-19]
          rotate: 0
  slimsplaydy_right_unrouted:
    outlines:
      main:
        outline: combo_right
    footprints:
      pg1316s:
        what: switch_pg1316s
        where: /^mirror/
        params:
          reversable: false
          side: 'F'
          from: "{{name}}"
          to: GND
      nicenano:
          what: mcu_nice_nano_smd
          where:
            ref: mirror_hand_inner_top
            shift: [18.5,-9]
            rotate: 0
          params:
            reverse_mount: true
            P1: mirror_hand_middle_top
            P1_label: D1
            P0: mirror_hand_index_top
            P0_label: D0
            P2: mirror_hand_inner_top
            P2_label: D2
            P3: mirror_hand_ring_top
            P3_label: D3
            P4: mirror_hand_pinky_top
            P4_label: D4
            P5: mirror_hand_middle_home
            P5_label: D5
            P6: mirror_hand_index_home
            P6_label: D6
            P7: mirror_hand_inner_home
            P7_label: D7
            P8: mirror_hand_ring_home
            P8_label: D8            
            P9: mirror_hand_pinky_home
            P9_label: D9
            P10: mirror_hand_pinky_bottom
            P10_label: D10
            P16: mirror_hand_middle_bottom
            P16_label: D16
            P14: mirror_hand_index_bottom
            P14_label: D14
            P15: mirror_hand_inner_bottom
            P15_label: D15
            P18: mirror_hand_ring_bottom
            P18_label: D18
            P19: mirror_thumb_near_fan
            P19_label: D19
            P20: mirror_thumb_far_fan
            P20_label: D20
            P21: D21
            P21_label: D21
            VCC: 3V3
            VCC_label: 3V3
            RAW: BAT
            RAW_label: BAT
      power:
        what: slider
        params:
          from: BAT_P
          to: BAT
        where:
          ref: mirror_hand_inner_bottom
          shift: [-53,-22]
          rotate: 180
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: mirror_hand_inner_bottom
          shift: [-35,-8]
          rotate: 0
      battcon:
        what: battery_connector_molex_pico_ezmate_1x02
        where:
          ref: mirror_hand_inner_bottom
          shift: [-56,-16 ]
          rotate: 90
      batsolder_neg:
        what: pad_single
        where:
          ref: mirror_hand_inner_bottom
          shift: [-59.75,-14.5]
          rotate: 0
        params:
          P1: GND
      batsolder_pos:
        what: pad_single
        where:
          ref: mirror_hand_inner_bottom
          shift: [-59.75,-17.5]
          rotate: 0
        params:
          P1: BAT_P
      battery:  
        what: battery_301230
        where:
          ref: mirror_hand_inner_bottom
          shift: [-30,-19]
          rotate: 0
  slimsplaydy_unrouted:
    outlines:
      left:
        outline: combo_left
      right:
        outline: combo_right
    footprints:
      pg1316s:
        what: switch_pg1316s
        where: true
        params:
          from: "{{name}}"
          to: GND
      nicenano_left:
          what: mcu_nice_nano_smd
          where:
            ref: hand_inner_top
            shift: [18.5,-9]
            rotate: 0
      power_left:
        what: slider
        params:
          from: BAT_P
          to: BAT
        where:
          ref: hand_inner_bottom
          shift: [-53,-22]
          rotate: 180
      battcon_left:
        what: battery_connector_molex_pico_ezmate_1x02
        where:
          ref: thumb_far_fan
          shift: [1,11]
          rotate: -90
      nicenano_right:
          what: mcu_nice_nano_smd
          where:
            ref: mirror_hand_inner_top
            shift: [18.5,-9]
            rotate: 0
      power_right:
        what: slider
        params:
          #intentionally reversed from left side for routing ease.
          from: BAT
          to: BAT_P
        where:
          ref: mirror_hand_inner_bottom
          shift: [-53,-22]
          rotate: 180
      battcon_right:
        what: battery_connector_molex_pico_ezmate_1x02
        where:
          ref: mirror_thumb_far_fan
          shift: [1,11]
          rotate: -90