units:
  # Proxy Spacing Variables
  # PG1316S keycaps are smaller than chocs...
  # According to https://docs.holykeebs.com/datasheets/PG1316_1U.pdf they are actually 16x16mm
  # but per Mike Holscher this 17x17 spacing works better.
  kx: 17
  ky: 17
  # Padding Variables
  px: kx + 2
  py: ky + 2
  $default_height: 17
  $default_width: 17
points:
  zones:
    hand:
      anchor.shift: [80,-160]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
        ring:
          key:
            stagger: 8
            splay: -4
            spread: kx+2
        middle:
          key:
            stagger: 7
            splay: -3
            spread: kx+1
        index:
          key:
            stagger: -4
            splay: -2
            spread: kx+0.8
        inner:
          key:
            stagger: -2
            splay: -1
            spread: kx+0.6
      rows:
        bottom:
        home:
        top:
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: hand_inner_bottom
        shift: [-2.5,-20]
      columns:
        near:
          key:
            splay: -15
        far:
          key:
            splay: -15
            shift: [3,-2]
      rows:
        fan:
  rotate: 10
  mirror: &mirror
    ref: thumb_far_fan
    distance: 3kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board_left:
    - what: polygon
      operation: stack
      points:
        - ref: thumb_far_fan
          shift: [9,-9] 
        - ref: hand_pinky_bottom
          shift: [36,-9]
        - ref: hand_pinky_bottom
          shift: [-9,-9]
        - ref: hand_pinky_top
          shift: [-9,9]
        - ref: hand_middle_top
          shift: [-9,9]
        - ref: hand_middle_top
          shift: [9,9]
        - ref: hand_inner_top
          shift: [9,9]
        - ref: hand_inner_top
          shift: [29,9]
        - ref: hand_inner_bottom
          shift: [29,-22.3]
      fillet: 3
  combo:
    - name: board_left
    - operation: subtract
      name: keys
  board_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_thumb_far_fan
          shift: [0.6px,-0.6py]
        - ref: mirror_hand_pinky_bottom
          shift: [38,-0.6py]
        - ref: mirror_hand_pinky_bottom
          shift: [-0.6px,-0.6py]
        - ref: mirror_hand_pinky_top
          shift: [-0.6px,0.5py]
        - ref: mirror_hand_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_hand_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_hand_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_hand_inner_top
          shift: [0.5px,0.5py]
        - ref: mirror_hand_inner_top
          shift: [35,0.5py]
        - ref: mirror_hand_inner_bottom
          shift: [35,-14]
      fillet: 8
  combo_right:
    - name: board_right
    - operation: subtract
      name: keys
pcbs:
  slimsplaydy_left_unrouted:
    outlines:
      main:
        outline: board_left
    footprints:
      pg1316s:
        what: switch_pg1316s
        where: /^hand|^thumb/
        params:
          from: GND
          to: "{{name}}"
      nicenano:
          what: mcu_nice_nano
          where:
            ref: hand_inner_top
            shift: [18.5,-9]
            rotate: 0
      power:
        what: slider
        params:
          from: BAT_P
          to: BAT
        where:
          ref: thumb_far_fan
          shift: [7.25,14]
          rotate: -90
      battcon:
        what: battery_connector_molex_pico_ezmate_1x02
        where:
          ref: thumb_far_fan
          shift: [1,11]
          rotate: -90
  slimsplaydy_right_unrouted:
    outlines:
      main:
        outline: board_right
    footprints:
      pg1316s:
        what: switch_pg1316s
        where: /^mirror/
        params:
          from: GND
          to: "{{name}}"
      nicenano:
          what: mcu_nice_nano
          where:
            ref: mirror_hand_inner_top
            shift: [19,-8.5]
            rotate: 0
      power:
        what: slider
        params:
          #intentionally reversed from left side for routing ease.
          from: BAT
          to: BAT_P
        where:
          ref: mirror_thumb_far_fan
          shift: [7.25,14]
          rotate: -90
      battcon:
        what: battery_connector_molex_pico_ezmate_1x02
        where:
          ref: mirror_thumb_far_fan
          shift: [1,11]
          rotate: -90
  slimsplaydy_unrouted:
    outlines:
      left:
        outline: board_left
      right:
        outline: board_right
    footprints:
      pg1316s:
        what: switch_pg1316s
        where: true
        params:
          from: GND
          to: "{{name}}"
      nicenano_left:
          what: mcu_nice_nano
          where:
            ref: hand_inner_top
            shift: [19,-8.5]
            rotate: 0
      power_left:
        what: slider
        params:
          from: BAT_P
          to: BAT
        where:
          ref: thumb_far_fan
          shift: [7.25,14]
          rotate: -90
      battcon_left:
        what: battery_connector_molex_pico_ezmate_1x02
        where:
          ref: thumb_far_fan
          shift: [1,11]
          rotate: -90
      nicenano_right:
          what: mcu_nice_nano
          where:
            ref: mirror_hand_inner_top
            shift: [19,-8.5]
            rotate: 0
      power_right:
        what: slider
        params:
          #intentionally reversed from left side for routing ease.
          from: BAT
          to: BAT_P
        where:
          ref: mirror_thumb_far_fan
          shift: [7.25,14]
          rotate: -90
      battcon_right:
        what: battery_connector_molex_pico_ezmate_1x02
        where:
          ref: mirror_thumb_far_fan
          shift: [1,11]
          rotate: -90